### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by fredericmazzini** [Brown-University-Library/django-shibboleth-remoteuser#73]
Hi,

Some of our shibboleth attributes contain accentuated characters (sn). They are incorrectly encoded when the corresponding user is created in the database.

Frédéric =>  FrÃ©dÃ©ric

What could be wrong in our configuration ?

Thank you for your help.

Fred

**Comment by bcail** [comment]
what database are you using, and what's the character set encoding on the database?

**Comment by fredericmazzini** [comment]
We're using PostgreSQL 9.6 and the database character set is UTF-8.

**Comment by bcail** [comment]
try adding a logging statement in ShibbolethRemoteUserMiddleware.parse_attributes() and see what values the headers have in Django request.META.

**Comment by bcail** [comment]
Are you on python 2 or 3? If 2, you need to make the log string explicitly unicode, instead of str.
If the data is garbled already in request.META, that's outside this project and we can close this issue. Then there may be an issue with how your webserver or Shibboleth is configured. You might want to make a very basic django project, with no dependencies, and make sure the Shib headers (in request.META) are correct. Then you can build from there.

**Comment by fredericmazzini** [comment]
I'm on python 3.6 and on django 2.0.7.
If I check the attributes value with the Shibboleth Session Handler they are correctly encoded. 
I have the feeling that Django interprets the values with a latin-1 charset. If I replace the statement shib_attrs[name] =  value by shib_attrs[name] =  bytearray(value, 'latin-1').decode('utf8') I get a correct value.

**Comment by bcail** [comment]
Check your django settings (or your environment or webserver locale) for anything that could be set to 'latin-1'. But if the data is garbled in request.META, that's outside this package. I'm going to close this issue.
