### ISSUE TITLE
Stale request

### ISSUE THREAD

**Issue by sternj** [Brown-University-Library/django-shibboleth-remoteuser#76]
When I add a "login_required" decoration to my view, Shibboleth tells me that my request is stale. Anyone ever dealt with this?

**Comment by bcail** [comment]
@sternj please give more details. Can you post the full traceback?

**Comment by sternj** [comment]
The docker-compose is located [here](https://github.com/sternj/dockerized-idp-testbed). Upon navigating to localhost/web (specified in the httpd-proxy container routing to the sp container), I get the following screen: 
![image](https://user-images.githubusercontent.com/19748383/44054544-d75bdb66-9f10-11e8-93ef-27b39626f1c1.png)

The text of the log starting from the request is this. Note that the configuration for that specific container is located in /sp/etc-httpd/conf.d/sp.conf
```
web_1            | [13/Aug/2018 19:49:51] "GET / HTTP/1.1" 302 0
sp_1             | sp-native 2018-08-13 19:49:51 WARN Shibboleth.Config : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp_1             | sp-native 2018-08-13 19:49:51 WARN Shibboleth.RequestMapper : DEPRECATED: legacy 2.0 configuration, support will be removed from a future version of the software
sp_1             | sp-native 2018-08-13 19:49:51 WARN Shibboleth.Application : handlerSSL should be enabled for SSL/TLS-enabled web sites
idp_1            | 2018-08-13 19:49:52,083 - ERROR [org.opensaml.profile.action.impl.DecodeMessage:73] - Profile Action DecodeMessage: Unable to decode incoming request
idp_1            | org.opensaml.messaging.decoder.MessageDecodingException: No SAMLRequest or SAMLResponse query path parameter, invalid SAML 2 HTTP Redirect message
idp_1            | 	at org.opensaml.saml.saml2.binding.decoding.impl.HTTPRedirectDeflateDecoder.doDecode(HTTPRedirectDeflateDecoder.java:108)
idp_1            | 2018-08-13 19:49:52,103 - WARN [org.opensaml.profile.action.impl.LogEvent:105] - A non-proceed event occurred while processing the request: UnableToDecode
ldap_1           | tail: '/var/log/dirsrv/slapd-dir/access' has been replaced;  following end of new file
ldap_1           | 	389-Directory/1.3.7.5 B2018.178.1311
ldap_1           | 	localhost:389 (/etc/dirsrv/slapd-dir)
ldap_1           | 
ldap_1           | [13/Aug/2018:19:49:31.833164994 +0000] conn=1 fd=64 slot=64 connection from 172.19.0.7 to 172.19.0.4
ldap_1           | [13/Aug/2018:19:49:31.833386548 +0000] conn=1 op=0 BIND dn="cn=admin,dc=idptestbed" method=128 version=3
ldap_1           | [13/Aug/2018:19:49:31.833821186 +0000] conn=1 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0000581104 dn="cn=admin,dc=idptestbed"
ldap_1           | [13/Aug/2018:19:49:31.834867868 +0000] conn=1 op=1 UNBIND
ldap_1           | [13/Aug/2018:19:49:31.834889716 +0000] conn=1 op=1 fd=64 closed - U1
idp_1            | 2018-08-13 19:50:34,852 - ERROR [org.opensaml.profile.action.impl.DecodeMessage:73] - Profile Action DecodeMessage: Unable to decode incoming request
idp_1            | org.opensaml.messaging.decoder.MessageDecodingException: No SAMLRequest or SAMLResponse query path parameter, invalid SAML 2 HTTP Redirect message
idp_1            | 	at org.opensaml.saml.saml2.binding.decoding.impl.HTTPRedirectDeflateDecoder.doDecode(HTTPRedirectDeflateDecoder.java:108)
idp_1            | 2018-08-13 19:50:34,854 - WARN [org.opensaml.profile.action.impl.LogEvent:105] - A non-proceed event occurred while processing the request: UnableToDecode


```

**Comment by bcail** [comment]
Try taking this package, and even django itself, out of the picture completely, and just make sure you can secure a URL with Shib. Once that's working, try django and this package again.

**Comment by sternj** [comment]
I can secure a URL with shib, navigating to / and clicking on the first link guarantees that

**Comment by bcail** [comment]
Yup, the issue could be with ProxyPass. For this package to work, you've got to be able to see REMOTE_USER (or some other header or environment variable you've configured) in request.META. When you secure a session with Shib, the REMOTE_USER env variable in Apache will be set (unless your shib is configured differently), and then Django can see it, and then this package can act on it.

You can remove this package completely, and just make sure that that REMOTE_USER header or environment variable is visible in request.META. If it's not visible, then the issue isn't anything in this package. And REMOTE_USER might not be set because of the ProxyPass setup, like you mention. We don't use this package with ProxyPass. You would need to pass through or set some header or environment variable in the request that actually gets to django - this might help: https://httpd.apache.org/docs/trunk/mod/mod_headers.html.

Here's how you would test it: set up your django app at /django_app. In your shib config, require a session for all /django_app URLs. When you visit it, you'll have to log in to shib. Then, you can see what's in your request.META information in the django view - there needs to be some information about the user that's logged in through shib. And this test doesn't require this package at all - it's just shib and django.

This page might be helpful: https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeAccess

**Comment by sternj** [comment]
I moved to a Flask implementation and ran into the same issue, I resolved it. 
For future people with the same problem-- I resolved the issue by putting a specific subpath of my Django site behind Shibboleth protection (in Apache) and having the login link be to there instead of to the actual SSO link (which is what caused the stale request.

@bcail thank you for your help!!!

**Comment by aescling** [comment]
> I moved to a Flask implementation and ran into the same issue, I resolved it. For future people with the same problem-- I resolved the issue by putting a specific subpath of my Django site behind Shibboleth protection (in Apache) and having the login link be to there instead of to the actual SSO link (which is what caused the stale request.
> 
> @bcail thank you for your help!!!

Hello. Sorry to ask this question six years later, and it&#x2019;s okay if you can&#x2019;t answer my question here, but I am running into this issue in a project at work, and it is a bit unclear to me what exactly you are saying you did?

When you say you changed the login link to a subpath under Shibboleth protection, do you mean the shib_view login link, or the in the project settings? The latter doesn&#x2019;t seem to me like a setting that should be changed as such (it should be pointing to the local SP login link); but changing the former still isn&#8217;t working for me. (Granted, I am using an Nginx setup instead of Apache for this project, so maybe there&#x2019;s an important subtlety there that I have missed?)

**Comment by sternj** [comment]
@aescling  Oh jeez, that was several lifetimes ago for me. I think we might not have used nginx at that point specifically because the Apache ecosystem was simply better documented with Shibboleth. What it looks to me like I was saying is that I both set the SSO login URL on the Django side of things and also configured that route in the Apache side of things, I believe this [commit that I made](https://github.com/sternj/dockerized-idp-testbed/commit/5f601ff10fc97b3d0350a7e237e8234e4b5a1811#diff-fb3fe6bb39b2dcfd91bbf9deda6349fd7bbd72c3cbc120871cec04576f949a5cR16) is most likely to be close to what I did.

 I can't speak to if this is the version where I finally got things working. I believe that my configuration likely is still live in my old department-- if you reach out to me (a few layers of indirection through my github profile and website), I could likely put you in touch with my old boss, who has likely touched the live code more recently.
